### PR TITLE
Remove master toleration from the node feature discovery worker

### PR DESCRIPTION
**Pull request by abdallahyas**
Override the default tolerations of the nfd so that they will be
missing the master toleration. This is needed to not deploy the MOFED
container on master node and having conflicts between the master and
worker MOFEDS.

### CODE REVIEW

**Comment by ykulazhenkov** [comment]
@AbdYsn It looks like the commit message doesn't reflect code changes. Could you please check it?

**Comment by abdallahyas** [comment]
> @AbdYsn It looks like the commit message doesn't reflect code changes. Could you please check it?

@ykulazhenkov Actually to remove the master toleration, the helm values default tolerations must be overwritten. To do that either we need to remove it from the repo, or override it by passing a new value of the toleration that does not have the master.

I choosed the later since we use the helm repo for deploying the GPU operator and i did not want to add a new step of cloning the GPU operator and removing the master toleration from the default values file.

In the end, i overrided the tolerations (both the gpu operator and the nic operator) with whatever is in the master repo minus the master toleration.

**Comment by abdallahyas** [comment]
So basically the final deployed operators would be missing the master toleration. which is IMO is what is described in the commit message, i can change it if you would like so that it describe the change more clearly. 

would be something like this
```
override the default tolerations of the nfd so that they will be missing the master toleration. This is needed to not
deploy the mofed container on master node and having conflicts.

**Comment by ykulazhenkov** [comment]
> > @AbdYsn It looks like the commit message doesn't reflect code changes. Could you please check it?
> 
> @ykulazhenkov Actually to remove the master toleration, the helm values default tolerations must be overwritten. To do that either we need to remove it from the repo, or override it by passing a new value of the toleration that does not have the master.
> 
> I choosed the later since we use the helm repo for deploying the GPU operator and i did not want to add a new step of cloning the GPU operator and removing the master toleration from the default values file.
> 
> In the end, i overrided the tolerations (both the gpu operator and the nic operator) with whatever is in the master repo minus the master toleration.

It sounds reasonable, but for me it is not clear from the code. Could you please add a short comment to the code that we overriding tollerations to remove master taint?

> So basically the final deployed operators would be missing the master toleration. which is IMO is what is described in the commit message, i can change it if you would like so that it describe the change more clearly.
> 
> would be something like this
> 
> ```
> override the default tolerations of the nfd so that they will be missing the master toleration. This is needed to not
> deploy the mofed container on master node and having conflicts.
> ```

I think it will be great to have such comment in code. I'm OK with current commit message

**Comment by abdallahyas** [comment]
> > > @AbdYsn It looks like the commit message doesn't reflect code changes. Could you please check it?
> > 
> > 
> > @ykulazhenkov Actually to remove the master toleration, the helm values default tolerations must be overwritten. To do that either we need to remove it from the repo, or override it by passing a new value of the toleration that does not have the master.
> > I choosed the later since we use the helm repo for deploying the GPU operator and i did not want to add a new step of cloning the GPU operator and removing the master toleration from the default values file.
> > In the end, i overrided the tolerations (both the gpu operator and the nic operator) with whatever is in the master repo minus the master toleration.
> 
> It sounds reasonable, but for me it is not clear from the code. Could you please add a short comment to the code that we overriding tollerations to remove master taint?
> 
> > So basically the final deployed operators would be missing the master toleration. which is IMO is what is described in the commit message, i can change it if you would like so that it describe the change more clearly.
> > would be something like this
> > ```
> > override the default tolerations of the nfd so that they will be missing the master toleration. This is needed to not
> > deploy the mofed container on master node and having conflicts.
> > ```
> 
> I think it will be great to have such comment in code. I'm OK with current commit message

will do

**Comment by abdallahyas** [comment]
@ykulazhenkov Done, also update the commit message  :).

**Comment by ykulazhenkov** [comment]
~~Do we need to override tolerations? Maybe it will be better to remove specific toleration with `yq` from template?~~
Example: 
`yq d <template_name>.yaml 'spec.template.spec.tolerations.(key==node-role.kubernetes.io/master)'`

Update: discussed offline. I missed that we edit helm values here, not manifests. Let's stay with current approach.

**Review by ykulazhenkov — APPROVED** [review]

**Review by e0ne — APPROVED** [review]

**Pull request merged**
