### PR TITLE
Move the repalcement of docker to sudo docker in make file

### PR DESCRIPTION
**Pull request by abdallahyas**
Move the replacement of docker to sudo docker in make file from
before the checkout command, to after it, to not have possible
confilicts with the checked out patch.

### CODE REVIEW

**Comment by adrianchiris** [comment]
@AbdYsn @e0ne  is there an issue with this PR or it just CI ?

can we move forward with this change ? also appreciate we do some downstream testing of this to make sure all is OK.

**Review by ykulazhenkov — APPROVED** [review]

**Comment by abdallahyas** [comment]
> @AbdYsn @e0ne is there an issue with this PR or it just CI ?
> 
> can we move forward with this change ? also appreciate we do some downstream testing of this to make sure all is OK.

It should only be CI, and from logs, the failures should not be related.
will test it downstream to make sure all works fine.

**Comment by abdallahyas** [comment]
@adrianchiris tested this patch with mellanox/network-operator#206 downstream, but it would fail, because it seems the network operator patch do a lot of changes to the Makefile including changing the way the image is deployed. so `make image` would fail

EDIT: and simply doing `/docker/sudo docker/` actually breaks the `Makefile`. So another patch is needed to support the network-operator patch

**Pull request merged**
