### PR TITLE
Add nic-operator hostdevice IB test

### PR DESCRIPTION
**Pull request by abdallahyas**
Added a test to test hostdevice plugin of the network operator with
infiniband interfaces. The test was added to the nic_operator_kind
project, and would test deploying two pods with infniband interfaces,
and test rping between the two pods using hostdevice plugin.

### CODE REVIEW

**Comment by abdallahyas** [comment]
This PR depends on https://github.com/Mellanox/kubernetes-ci/pull/139.
The other patch is needed to switch the setup to be a mixed ethernet and infiniband setup.

**Review by e0ne — APPROVED** [review]

**Review by ykulazhenkov — APPROVED** [review]

**Pull request merged**
