### PR TITLE
Support sudo limited priviliges in the project

### PR DESCRIPTION
**Pull request by abdallahyas**
Modify the project to support sudo limited privileges.

### CODE REVIEW

**Comment by abdallahyas** [comment]
The WIP is because not all projects are tested, currently the tested projects are:
 * nic-operator
 * nic-operator_kind
 * nic-operator_helm
 * ovn-kubernetes

**Review by e0ne — APPROVED** [review]

**Review by ykulazhenkov — APPROVED** [review]

**Pull request merged**
