### PR TITLE
Workaround setting the vfs macs for the sriov-operator sriovs VFs

### PR DESCRIPTION
**Pull request by abdallahyas**
Sometimes sriov-network-operator inside network-operator in kind
cluster fails to set the VFs node GUIDS, this will cause the RDMA
traffic to fail between pods that use these VFs.

This patch workaround this by setting the VFs node GUIDs manually.
This workaround should not be nessacary in master sriov-network-operator
images, so it should be removed when a new iamge of the sriov-operator
is applied in the network-operator CIs,

### CODE REVIEW

**Comment by abdallahyas** [comment]
This patch affects the nic-operator-helm ci

**Comment by abdallahyas** [comment]
@e0ne This would stabilize the helm CI

**Review by e0ne — APPROVED** [review]

**Comment by abdallahyas** [comment]
doing one last test to make sure there is no other issues

**Comment by abdallahyas** [comment]
merging this patch to stabilize the helm CI

**Pull request merged**
