### PR TITLE
Implement the new project hierarchy

### LINKED ISSUE #41: Create some project heirarchy
We should have some sort of hierarchy for the project

e.g
have common  and per cni folders

### PR DESCRIPTION
**Pull request by abdallahyas**
Implemented the new project hierarchy, such that each project will
have its own directory, and in each directory, there will be three
scripts: start, test, and stop.

  fixes #41

### CODE REVIEW

**Comment by abdallahyas** [comment]
retest-sriov_ib

**Comment by moshe010** [comment]
this have merge conflict and also why it has 3 pending jobs. Please check this

**Review by moshe010 — APPROVED** [review]

**Review by moshe010 — CHANGES_REQUESTED** [review]
Please fix merge conflict

**Comment by abdallahyas** [comment]
@moshe010 , this is ready

**Review by moshe010 — APPROVED** [review]

**Pull request merged**
